[package]
name = "goldbach_other_conj"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
custom_math_utilities = { path = "../custom_math_utilities"}