[package]
name = "square_root_convergence"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"
custom_math_utilities = { path = "../custom_math_utilities"}